### Создание файла
POST {{host}}/api/v1/init/
Content-Type: application/json

{
  "url": "http://www.file.url",
  "auth_url": "artstation/shmel",
  "service": "artstation"
}

### Создание файла
POST {{host}}/api/v1/proxy/
Content-Type: application/json

{
  "url": "http://www.file.url",
  "auth_url": "artstation/shmel",
  "service": "artstation"
}
